export const SET_ACTIVE_USER_ID = "SET_ACTIVE_USER_ID";
export const UNSET_ACTIVE_USER = "UNSET_ACTIVE_USER";
export const SET_TYPING_VALUE = "SET_TYPING_VALUE";
export const SEND_MESSAGE = "SEND_MESSAGE";
export const DELETE_MESSAGE = "DELETE_MESSAGE";
export const EDIT_MESSAGE = "EDIT_MESSAGE";
export const EDITED_MESSAGE = "EDITED_MESSAGE";
export const DETAILS_INFO = "DETAILS_INFO";

//auth actionTypes
export const REQUEST_SIGNUP_START = "REQUEST_SIGNUP_START";
export const REQUEST_SIGNUP_SUCCESS = "REQUEST_SIGNUP_SUCCESS";
export const REQUEST_SIGNUP_FAIL = "REQUEST_SIGNUP_FAIL";

export const REQUEST_USERLOGIN_START = "REQUEST_USERLOGIN_START";
export const REQUEST_USERLOGIN_SUCCESS = "REQUEST_USERLOGIN_SUCCESS";
export const REQUEST_USERLOGIN_FAIL = "REQUEST_USERLOGIN_FAIL";

export const SIGNOUT_START = "SIGNOUT"
export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS"
export const SIGNOUT_FAIL = "SIGNOUT_FAIL"